indexing

In [11]:
import numpy as np
a=[1,2,3,4,5,6]
b=np.array(a)
print(a[3])
print(a[-3])
print(a)
print(a[5])

4
4
[1, 2, 3, 4, 5, 6]
6


SLicing

In [24]:
import numpy as np
a=[1,-2,4,6.2,'abc',True]
b=np.array(a)
print("1:",a[2:4])
print("2:",a[3:7])
print("3:",a[0:7])
print("4:",a[ :4])
print("5:",a[0:])
print("6:",a[ : ])
print("7:",a[2:7:2])
print("8:",a[-4:-2])
print("9:",a[-2:-4])
print("10:",a[4:2])
print("11:",a[-4:-2:-2])





1: [4, 6.2]
2: [6.2, 'abc', True]
3: [1, -2, 4, 6.2, 'abc', True]
4: [1, -2, 4, 6.2]
5: [1, -2, 4, 6.2, 'abc', True]
6: [1, -2, 4, 6.2, 'abc', True]
7: [4, 'abc']
8: [4, 6.2]
9: []
10: []
11: []


Zero's method

In [31]:
import numpy as np
a=np.zeros((4,3))
print(a)
b=np.zeros(4)
print(b)
c=np.zeros(4,dtype=int)
print(c)
d=np.zeros((4,2),dtype=int)
print(d)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0.]
[0 0 0 0]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


One's method

In [35]:
import numpy as np
a=np.ones((2,3))
print(a)
b=np.ones(2)
print(b)
c=np.ones((2,3),dtype=int)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]
[[1 1 1]
 [1 1 1]]


Eye method

In [39]:
import numpy as py
a=py.eye(1,5,3)
print(a)
b=py.eye(5,5,1)
print(b)
c=py.eye(5,5,4)
print(c)

[[0. 0. 0. 1. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
